import { MembershipProvider } from "@/providers/membership-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const membership = {
    name: "basic",
    ability: ["social", "commerce"],
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <MembershipProvider ability={membership.ability}>
          {children}
        </MembershipProvider>
      </body>
    </html>
  );
}
